### PR TITLE
Fix overclocking

### PR DESCRIPTION
**Pull request by MichaelBell**
Don't do page boundary crossing writes to the PSRAM.  Scale SWD clock divisor based on system clock.

I can now run MicroPython examples at 270MHz on my PicoVision, YMMV!

### CODE REVIEW

**Comment by MichaelBell** [comment]
Doh, this breaks unaligned writes.  Please don't merge, and I'll see if I can sort it out at some point.

**Comment by Daft-Freak** [comment]
Ooh, this should let me delete a hack :thinking:

**Comment by MichaelBell** [comment]
If you're only doing aligned writes (writes to PSRAM addresses = 0 mod 4) then you should just be able to run with this PR applied and have no problems.

Maybe we should merge the SWD half of this change so that at least that works at the higher clock speed, and then you're only problem is the page crossing writes themselves failing, which for me doesn't seem to happen until around 240MHz

**Comment by MichaelBell** [comment]
The extra work to avoid page crossing writes degraded vector clock performance a bit.  The latest commit gets that back and a little bit more, by splitting the functions that benefit from higher optimization levels out and compiling them with -O2 instead of -Os.

**Comment by Gadgetoid** [comment]
Safe to merge now? I'd like to merge down and spin up a fresh dev branch.

**Pull request merged**
