### PR TITLE
Fix occasional split of red and green channels from blue channel

### PR DESCRIPTION
**Pull request by MichaelBell**
It looks like the DVI transmit FIFOs were running out of data in 400x300 mode, probably just at the very start of signal generation, but this caused everything to get misaligned - issue #88 

Fixed by giving DMA transfers more priority on the bus.

### CODE REVIEW

**Comment by mikerr** [comment]
Tried this (widescreen version)  on 400x300 and 800x600 and it's "99%" fixed

I.e. one in 5-10 restarts will have a 1 pixel yellow bar on the left and 1 pixel misalignment.

**Comment by MichaelBell** [comment]
I can't reproduce this at all any more, but I've found another priority bit to set, so let's see if that does the trick!

@mikerr please could you give this latest version a test?

**Comment by mikerr** [comment]
Loaded up that one and counted the resets:

Over 20 restarts I got the yellow line / 1 pixel offset 4 times
one per second - on 4,5, 9 and 20th times 

Note at no point did I get big offsets  (20-30 pixels) like I was getting in the release .uf2

**Comment by MichaelBell** [comment]
OK thanks, that sounds like basically the same as without the second commit then.

**Comment by MichaelBell** [comment]
The first commit is included in the version of pico-stick that's in #93, I've removed the second commit as it didn't help (and in fact might have made things slightly worse).  So closing this PR for now (but #88 remains open to investigate the remaining small offset).

**Pull request closed without merging**
